#!/bin/bash
#
# Dragonfly Installation Script for Ravact
# Installs Dragonfly - Modern Redis/Memcached replacement
#

set -e  # Exit on error

echo "=========================================="
echo "  Dragonfly Installation"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root"
    exit 1
fi

# Detect distribution
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    VERSION=$VERSION_ID
else
    echo "Error: Cannot detect OS distribution"
    exit 1
fi

echo "Detected OS: $OS $VERSION"
echo ""

# Detect architecture
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)
        ARCH_NAME="x86_64"
        ;;
    aarch64|arm64)
        ARCH_NAME="aarch64"
        ;;
    *)
        echo "Error: Unsupported architecture: $ARCH"
        echo "Dragonfly supports x86_64 and aarch64 only"
        exit 1
        ;;
esac

echo "Architecture: $ARCH_NAME"
echo ""

# Set Dragonfly version (can be overridden via environment)
DRAGONFLY_VERSION="${DRAGONFLY_VERSION:-v1.14.0}"

# Update package list
echo "Updating package list..."
case "$OS" in
    ubuntu|debian)
        apt-get update -qq
        ;;
    centos|rhel|fedora)
        yum update -y -q
        ;;
esac

# Install dependencies
echo "Installing dependencies..."
case "$OS" in
    ubuntu|debian)
        apt-get install -y wget curl
        ;;
    centos|rhel|fedora)
        yum install -y wget curl
        ;;
esac

# Installation method - default to binary (recommended)
# Set DRAGONFLY_INSTALL_METHOD=2 for Docker installation
install_method="${DRAGONFLY_INSTALL_METHOD:-1}"
echo "Installation method: $([ "$install_method" = "2" ] && echo "Docker" || echo "Binary (Recommended)")"

if [ "$install_method" = "1" ]; then
    # Binary Installation
    echo ""
    echo "Installing Dragonfly binary..."
    
    # Download binary
    DRAGONFLY_URL="https://github.com/dragonflydb/dragonfly/releases/download/${DRAGONFLY_VERSION}/dragonfly-${ARCH_NAME}.tar.gz"
    
    echo "Downloading from: $DRAGONFLY_URL"
    wget -q "$DRAGONFLY_URL" -O /tmp/dragonfly.tar.gz
    
    # Extract binary
    tar -xzf /tmp/dragonfly.tar.gz -C /tmp/
    mv /tmp/dragonfly-${ARCH_NAME} /usr/local/bin/dragonfly
    chmod +x /usr/local/bin/dragonfly
    rm /tmp/dragonfly.tar.gz
    
    echo "✓ Binary installed to /usr/local/bin/dragonfly"
    
    # Create dragonfly user
    if ! id -u dragonfly > /dev/null 2>&1; then
        useradd -r -s /bin/false dragonfly
        echo "✓ Created dragonfly user"
    fi
    
    # Create directories
    mkdir -p /var/lib/dragonfly
    mkdir -p /var/log/dragonfly
    mkdir -p /etc/dragonfly
    
    chown -R dragonfly:dragonfly /var/lib/dragonfly
    chown -R dragonfly:dragonfly /var/log/dragonfly
    
    echo "✓ Created directories"
    
    # Create configuration file
    cat > /etc/dragonfly/dragonfly.conf << 'EOF'
# Dragonfly Configuration
# Generated by Ravact

# Bind address (0.0.0.0 for all interfaces, 127.0.0.1 for localhost only)
bind 127.0.0.1

# Port
port 6379

# Working directory
dir /var/lib/dragonfly

# Log file
logfile /var/log/dragonfly/dragonfly.log

# Max memory (in bytes, 0 for unlimited)
# Recommended: 75% of system RAM
maxmemory 0

# Snapshot frequency (save DB to disk)
# save <seconds> <changes>
save 900 1
save 300 10
save 60 10000

# Require password authentication
# requirepass your_secure_password_here

# Enable cluster mode (for multi-node setup)
# cluster_mode enabled

# Number of threads (auto-detected by default)
# proactor_threads auto
EOF
    
    echo "✓ Created configuration file: /etc/dragonfly/dragonfly.conf"
    
    # Create systemd service
    cat > /etc/systemd/system/dragonfly.service << 'EOF'
[Unit]
Description=Dragonfly In-Memory Data Store
After=network.target

[Service]
Type=simple
User=dragonfly
Group=dragonfly
ExecStart=/usr/local/bin/dragonfly --logtostderr --dir /var/lib/dragonfly
Restart=always
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
    
    echo "✓ Created systemd service"
    
    # Reload systemd
    systemctl daemon-reload
    
    # Enable and start Dragonfly
    echo ""
    echo "Starting Dragonfly service..."
    systemctl enable dragonfly
    systemctl start dragonfly
    
    # Wait for Dragonfly to be ready
    echo "Waiting for Dragonfly to be ready..."
    sleep 3
    
    # Check if Dragonfly is running
    if systemctl is-active --quiet dragonfly; then
        echo ""
        echo "✓ Dragonfly installed and running successfully!"
        
        # Get version
        DRAGONFLY_VERSION_FULL=$(dragonfly --version 2>&1 | grep -oP 'version \K[0-9.]+' || echo "$DRAGONFLY_VERSION")
        echo "✓ Dragonfly version: $DRAGONFLY_VERSION_FULL"
        
        # Test connection
        if command -v redis-cli &> /dev/null; then
            if redis-cli -p 6379 ping 2>/dev/null | grep -q PONG; then
                echo "✓ Dragonfly is responding to Redis commands"
            fi
        else
            echo "! redis-cli not installed (optional for testing)"
        fi
        
        echo ""
        echo "=========================================="
        echo "  Installation Complete!"
        echo "=========================================="
        echo ""
        echo "Dragonfly is running on:"
        echo "  Address: 127.0.0.1"
        echo "  Port: 6379"
        echo ""
        echo "Configuration:"
        echo "  Config: /etc/dragonfly/dragonfly.conf"
        echo "  Data: /var/lib/dragonfly"
        echo "  Logs: /var/log/dragonfly/dragonfly.log"
        echo ""
        echo "Service management:"
        echo "  systemctl status dragonfly"
        echo "  systemctl restart dragonfly"
        echo "  systemctl stop dragonfly"
        echo ""
        echo "Connect using Redis clients:"
        echo "  redis-cli -h 127.0.0.1 -p 6379"
        echo "  redis-cli ping"
        echo ""
        echo "Features:"
        echo "  • Redis-compatible protocol"
        echo "  • Multi-threaded architecture"
        echo "  • Lower memory footprint"
        echo "  • Higher throughput than Redis"
        echo "  • Supports Redis commands"
        echo ""
        echo "Next steps:"
        echo "  • Configure password in /etc/dragonfly/dragonfly.conf"
        echo "  • Adjust maxmemory for your needs"
        echo "  • Update application to use port 6379"
        echo "  • Enable persistence if needed (already configured)"
        echo ""
        echo "Documentation:"
        echo "  https://www.dragonflydb.io/docs"
        echo ""
    else
        echo ""
        echo "✗ Error: Dragonfly service failed to start"
        echo "Check logs: journalctl -u dragonfly -n 50"
        exit 1
    fi
    
elif [ "$install_method" = "2" ]; then
    # Docker Installation
    echo ""
    echo "Installing Dragonfly via Docker..."
    
    # Check if Docker is installed
    if ! command -v docker &> /dev/null; then
        echo "Docker not found. Installing Docker..."
        
        case "$OS" in
            ubuntu|debian)
                apt-get install -y ca-certificates curl gnupg
                install -m 0755 -d /etc/apt/keyrings
                curl -fsSL https://download.docker.com/linux/$OS/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
                chmod a+r /etc/apt/keyrings/docker.gpg
                
                echo \
                  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$OS \
                  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
                  tee /etc/apt/sources.list.d/docker.list > /dev/null
                
                apt-get update -qq
                apt-get install -y docker-ce docker-ce-cli containerd.io
                ;;
            centos|rhel|fedora)
                yum install -y yum-utils
                yum-config-manager --add-repo https://download.docker.com/linux/$OS/docker-ce.repo
                yum install -y docker-ce docker-ce-cli containerd.io
                systemctl start docker
                systemctl enable docker
                ;;
        esac
        
        echo "✓ Docker installed"
    fi
    
    # Create directories
    mkdir -p /var/lib/dragonfly
    
    # Run Dragonfly container
    echo ""
    echo "Starting Dragonfly Docker container..."
    
    docker run -d \
        --name dragonfly \
        --restart unless-stopped \
        -p 6379:6379 \
        -v /var/lib/dragonfly:/data \
        docker.dragonflydb.io/dragonflydb/dragonfly:${DRAGONFLY_VERSION}
    
    # Wait for container to be ready
    sleep 3
    
    # Check if container is running
    if docker ps | grep -q dragonfly; then
        echo ""
        echo "✓ Dragonfly Docker container running successfully!"
        
        echo ""
        echo "=========================================="
        echo "  Installation Complete!"
        echo "=========================================="
        echo ""
        echo "Dragonfly is running in Docker on:"
        echo "  Address: 127.0.0.1"
        echo "  Port: 6379"
        echo ""
        echo "Container management:"
        echo "  docker ps                      # View containers"
        echo "  docker logs dragonfly          # View logs"
        echo "  docker restart dragonfly       # Restart"
        echo "  docker stop dragonfly          # Stop"
        echo "  docker start dragonfly         # Start"
        echo ""
        echo "Connect using Redis clients:"
        echo "  redis-cli -h 127.0.0.1 -p 6379"
        echo "  redis-cli ping"
        echo ""
        echo "Data directory:"
        echo "  /var/lib/dragonfly (mounted in container)"
        echo ""
    else
        echo ""
        echo "✗ Error: Dragonfly container failed to start"
        echo "Check logs: docker logs dragonfly"
        exit 1
    fi
fi

exit 0
