#!/bin/bash
#
# FrankenPHP Installation Script for Ravact
# Installs FrankenPHP with Caddy web server (Classic, Worker, and Mercure modes)
# Supports multiple sites configuration
#

set -e  # Exit on error

echo "=========================================="
echo "  FrankenPHP Installation"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root"
    exit 1
fi

# Detect distribution
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
    VERSION=$VERSION_ID
else
    echo "Error: Cannot detect OS distribution"
    exit 1
fi

echo "Detected OS: $OS $VERSION"
echo ""

# Detect architecture
ARCH=$(uname -m)
case "$ARCH" in
    x86_64)
        ARCH_NAME="x86_64"
        ;;
    aarch64|arm64)
        ARCH_NAME="aarch64"
        ;;
    *)
        echo "Error: Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

echo "Architecture: $ARCH_NAME"
echo ""

# Update package list
echo "Updating package list..."
case "$OS" in
    ubuntu|debian)
        apt-get update -qq
        apt-get install -y wget curl tar
        ;;
    centos|rhel|fedora)
        yum update -y -q
        yum install -y wget curl tar
        ;;
esac

# Download and install FrankenPHP
echo "Downloading FrankenPHP..."
FRANKENPHP_VERSION="${FRANKENPHP_VERSION:-1.1.0}"
DOWNLOAD_URL="https://github.com/dunglas/frankenphp/releases/download/v${FRANKENPHP_VERSION}/frankenphp-linux-${ARCH_NAME}"

wget -q "$DOWNLOAD_URL" -O /usr/local/bin/frankenphp
chmod +x /usr/local/bin/frankenphp

echo "✓ FrankenPHP binary installed"

# Verify installation
FRANKENPHP_VERSION_FULL=$(/usr/local/bin/frankenphp version | grep -oP 'v\K[0-9.]+' || echo "$FRANKENPHP_VERSION")
echo "✓ FrankenPHP version: $FRANKENPHP_VERSION_FULL"

# Create frankenphp user
if ! id -u frankenphp > /dev/null 2>&1; then
    useradd -r -s /bin/false frankenphp
    echo "✓ Created frankenphp user"
fi

# Create directory structure
mkdir -p /etc/frankenphp/sites-available
mkdir -p /etc/frankenphp/sites-enabled
mkdir -p /var/www
mkdir -p /var/log/frankenphp

echo "✓ Created directory structure"

# Create main Caddyfile
cat > /etc/frankenphp/Caddyfile << 'EOF'
# FrankenPHP Main Configuration
# Generated by Ravact

{
    # Global options
    auto_https off
    admin off
    
    # FrankenPHP worker options
    frankenphp {
        # Number of workers per site (0 = disabled, use classic mode)
        # Set per site or globally
        num_threads 2
    }
}

# Import site configurations
import /etc/frankenphp/sites-enabled/*.caddy
EOF

echo "✓ Created main Caddyfile"

# Create example site configurations for each mode

# 1. Classic Mode (Traditional PHP-FPM style)
cat > /etc/frankenphp/sites-available/example-classic.caddy << 'EOF'
# Classic Mode - Traditional PHP execution
# Copy and modify this file for your site
# Enable: ln -s /etc/frankenphp/sites-available/example-classic.caddy /etc/frankenphp/sites-enabled/

example-classic.local {
    root * /var/www/example-classic
    
    # PHP handling (classic mode - no workers)
    php_server
    
    # File server for static files
    file_server
    
    # Logs
    log {
        output file /var/log/frankenphp/example-classic-access.log
        format json
    }
    
    # Security headers
    header {
        X-Frame-Options "SAMEORIGIN"
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
    }
}
EOF

# 2. Worker Mode (High performance for Laravel/Symfony)
cat > /etc/frankenphp/sites-available/example-worker.caddy << 'EOF'
# Worker Mode - High Performance with Application Workers
# Best for Laravel, Symfony, and other modern PHP frameworks
# Copy and modify this file for your site
# Enable: ln -s /etc/frankenphp/sites-available/example-worker.caddy /etc/frankenphp/sites-enabled/

example-worker.local {
    root * /var/www/example-worker/public
    
    # PHP with workers (high performance)
    php_server {
        # Number of workers for this site
        workers 4
        
        # Worker script (for Laravel, use public/index.php)
        worker_script index.php
    }
    
    # Handle Laravel routing
    @notStatic {
        not path *.css *.js *.png *.jpg *.gif *.svg *.ico *.woff *.woff2
        file {
            try_files {path} /index.php
        }
    }
    
    # Rewrite to index.php for non-static files
    rewrite @notStatic /index.php
    
    # File server for static files
    file_server
    
    # Logs
    log {
        output file /var/log/frankenphp/example-worker-access.log
        format json
    }
    
    # Security headers
    header {
        X-Frame-Options "SAMEORIGIN"
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
    }
}
EOF

# 3. Mercure Mode (Real-time capabilities with Caddy + Mercure)
cat > /etc/frankenphp/sites-available/example-mercure.caddy << 'EOF'
# Mercure Mode - Real-time Push with Caddy + Mercure
# For applications requiring real-time updates
# Copy and modify this file for your site
# Enable: ln -s /etc/frankenphp/sites-available/example-mercure.caddy /etc/frankenphp/sites-enabled/

example-mercure.local {
    root * /var/www/example-mercure/public
    
    # Mercure hub configuration
    mercure {
        # Publisher JWT key (change this!)
        publisher_jwt {
            key "!ChangeThisMercureHubJWTSecretKey!"
            algorithm HS256
        }
        
        # Subscriber JWT key
        subscriber_jwt {
            key "!ChangeThisMercureHubJWTSecretKey!"
            algorithm HS256
        }
        
        # Allow anonymous subscriptions (change for production)
        anonymous
        
        # CORS
        cors_origins *
    }
    
    # PHP with workers
    php_server {
        workers 4
        worker_script index.php
    }
    
    # Handle routing
    @notStatic {
        not path *.css *.js *.png *.jpg *.gif *.svg *.ico *.woff *.woff2
        not path /.well-known/mercure
        file {
            try_files {path} /index.php
        }
    }
    
    rewrite @notStatic /index.php
    
    # File server
    file_server
    
    # Logs
    log {
        output file /var/log/frankenphp/example-mercure-access.log
        format json
    }
    
    # Security headers
    header {
        X-Frame-Options "SAMEORIGIN"
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
    }
}
EOF

# 4. Multi-site example with multiple modes
cat > /etc/frankenphp/sites-available/multi-site-example.caddy << 'EOF'
# Multi-Site Configuration Example
# This shows how to run multiple sites with different modes

# Site 1: Classic Mode
site1.example.com {
    root * /var/www/site1
    php_server
    file_server
    log {
        output file /var/log/frankenphp/site1-access.log
    }
}

# Site 2: Worker Mode (Laravel)
site2.example.com {
    root * /var/www/site2/public
    php_server {
        workers 4
        worker_script index.php
    }
    @notStatic {
        not path *.css *.js *.png *.jpg *.gif *.svg *.ico
        file {
            try_files {path} /index.php
        }
    }
    rewrite @notStatic /index.php
    file_server
    log {
        output file /var/log/frankenphp/site2-access.log
    }
}

# Site 3: Mercure Mode (Real-time)
site3.example.com {
    root * /var/www/site3/public
    mercure {
        publisher_jwt {
            key "!ChangeThisMercureHubJWTSecretKey!"
            algorithm HS256
        }
        subscriber_jwt {
            key "!ChangeThisMercureHubJWTSecretKey!"
            algorithm HS256
        }
        anonymous
    }
    php_server {
        workers 2
        worker_script index.php
    }
    @notStatic {
        not path *.css *.js *.png *.jpg *.gif *.svg *.ico
        not path /.well-known/mercure
        file {
            try_files {path} /index.php
        }
    }
    rewrite @notStatic /index.php
    file_server
    log {
        output file /var/log/frankenphp/site3-access.log
    }
}
EOF

echo "✓ Created example site configurations"

# Create systemd service
cat > /etc/systemd/system/frankenphp.service << 'EOF'
[Unit]
Description=FrankenPHP Server
Documentation=https://frankenphp.dev
After=network.target network-online.target
Requires=network-online.target

[Service]
Type=notify
User=root
Group=root
ExecStart=/usr/local/bin/frankenphp run --config /etc/frankenphp/Caddyfile
ExecReload=/bin/kill -USR1 $MAINPID
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOF

echo "✓ Created systemd service"

# Reload systemd
systemctl daemon-reload

# Create helper script for managing sites
cat > /usr/local/bin/frankenphp-site << 'EOF'
#!/bin/bash
# FrankenPHP Site Management Helper

SITES_AVAILABLE="/etc/frankenphp/sites-available"
SITES_ENABLED="/etc/frankenphp/sites-enabled"

case "$1" in
    enable)
        if [ -z "$2" ]; then
            echo "Usage: frankenphp-site enable <site>"
            exit 1
        fi
        SITE="$2"
        if [ ! -f "$SITES_AVAILABLE/$SITE" ]; then
            echo "Error: Site configuration not found: $SITES_AVAILABLE/$SITE"
            exit 1
        fi
        ln -sf "$SITES_AVAILABLE/$SITE" "$SITES_ENABLED/$SITE"
        echo "✓ Enabled site: $SITE"
        echo "Reload FrankenPHP to apply: systemctl reload frankenphp"
        ;;
    disable)
        if [ -z "$2" ]; then
            echo "Usage: frankenphp-site disable <site>"
            exit 1
        fi
        SITE="$2"
        rm -f "$SITES_ENABLED/$SITE"
        echo "✓ Disabled site: $SITE"
        echo "Reload FrankenPHP to apply: systemctl reload frankenphp"
        ;;
    list)
        echo "Available sites:"
        ls -1 "$SITES_AVAILABLE" | sed 's/^/  /'
        echo ""
        echo "Enabled sites:"
        ls -1 "$SITES_ENABLED" 2>/dev/null | sed 's/^/  /' || echo "  (none)"
        ;;
    *)
        echo "FrankenPHP Site Management"
        echo ""
        echo "Usage:"
        echo "  frankenphp-site enable <site>   - Enable a site"
        echo "  frankenphp-site disable <site>  - Disable a site"
        echo "  frankenphp-site list            - List all sites"
        echo ""
        echo "Example:"
        echo "  frankenphp-site enable example-worker.caddy"
        echo "  systemctl reload frankenphp"
        ;;
esac
EOF

chmod +x /usr/local/bin/frankenphp-site

echo "✓ Created site management helper"

# Start FrankenPHP
echo ""
echo "Starting FrankenPHP..."
systemctl enable frankenphp
systemctl start frankenphp

# Wait and check status
sleep 2

if systemctl is-active --quiet frankenphp; then
    echo ""
    echo "✓ FrankenPHP installed and running successfully!"
    
    echo ""
    echo "=========================================="
    echo "  Installation Complete!"
    echo "=========================================="
    echo ""
    echo "FrankenPHP Features:"
    echo "  • Standalone PHP + Caddy web server"
    echo "  • Three operation modes: Classic, Worker, Mercure"
    echo "  • Multi-site support"
    echo "  • Automatic HTTPS with Caddy"
    echo "  • Early Hints support"
    echo "  • Real-time push with Mercure"
    echo ""
    echo "Configuration:"
    echo "  Main config: /etc/frankenphp/Caddyfile"
    echo "  Sites available: /etc/frankenphp/sites-available/"
    echo "  Sites enabled: /etc/frankenphp/sites-enabled/"
    echo "  Logs: /var/log/frankenphp/"
    echo ""
    echo "Site Management:"
    echo "  frankenphp-site list                    # List all sites"
    echo "  frankenphp-site enable example.caddy    # Enable a site"
    echo "  frankenphp-site disable example.caddy   # Disable a site"
    echo "  systemctl reload frankenphp             # Apply changes"
    echo ""
    echo "Service Management:"
    echo "  systemctl status frankenphp    # Check status"
    echo "  systemctl restart frankenphp   # Restart"
    echo "  systemctl reload frankenphp    # Reload config"
    echo "  systemctl stop frankenphp      # Stop"
    echo ""
    echo "Example Site Configurations:"
    echo "  • example-classic.caddy  - Classic PHP mode"
    echo "  • example-worker.caddy   - Worker mode (Laravel/Symfony)"
    echo "  • example-mercure.caddy  - Mercure real-time mode"
    echo "  • multi-site-example.caddy - Multiple sites example"
    echo ""
    echo "Next Steps:"
    echo ""
    echo "1. Create your site directory:"
    echo "   mkdir -p /var/www/mysite/public"
    echo ""
    echo "2. Copy and customize a site config:"
    echo "   cp /etc/frankenphp/sites-available/example-worker.caddy \\"
    echo "      /etc/frankenphp/sites-available/mysite.caddy"
    echo "   # Edit mysite.caddy with your domain and settings"
    echo ""
    echo "3. Enable the site:"
    echo "   frankenphp-site enable mysite.caddy"
    echo "   systemctl reload frankenphp"
    echo ""
    echo "4. Test your site:"
    echo "   curl -H 'Host: your-domain.com' http://localhost"
    echo ""
    echo "Documentation:"
    echo "  https://frankenphp.dev"
    echo ""
else
    echo ""
    echo "✗ Error: FrankenPHP service failed to start"
    echo "Check logs: journalctl -u frankenphp -n 50"
    exit 1
fi

exit 0
